SELECT * FROM Accounts
SELECT * FROM Phones

CREATE TABLE Accounts(
   ID TEXT NOT NULL PRIMARY KEY,
   SURNAME TEXT NOT NULL,
   NAME TEXT NOT NULL,
   MIDDLENAME TEXT NOT NULL,
   GENDER INT NOT NULL,
   BIRTHDAY DATETIME NOT NULL,
   COUNTRY TEXT NOT NULL,
   REGION TEXT NOT NULL,
   CITY TEXT NOT NULL,
   ADDRESS TEXT NOT NULL,
   EMAIL TEXT NOT NULL,
   ASFOUND TEXT NOT NULL
)

CREATE TABLE Phones(
   PHONE TEXT NOT NULL,
   ACCOUNT_ID TEXT NOT NULL,
   FOREIGN KEY (ACCOUNT_ID) REFERENCES Accounts(ID)
)